---
title: "ICPMS_7d_Expt"
author: "Roy W. Martin"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(readxl)
library(ggpubr)
library(moments)
library(ggplot2)
library(ggExtra)
library(gridExtra)
library(kableExtra)
library(ggrepel)
library(dplyr)
library(tidyverse)
library(tidyr)
library(future)
library(foreach)
library(itertools)
library(bayesplot)
library(tidybayes)
library(brms)

options(mc.cores = parallel::detectCores(logical = FALSE))
options( max.print = 1000 )

# stat: skew 
skew <- function(x) {
  xdev <- x - mean(x)
  n <- length(x)
  r <- sum(xdev^3) / sum(xdev^2)^1.5
  return(r * sqrt(n) * (1 - 1/n)^1.5)
}

# Load model and data files for knitting (if they already exist)
#f1 <- "C:/Users/rmartin/OneDrive - Environmental Protection Agency (EPA)/Documents/AE_Reservoirs/DissolvedGasNla/modelFiles/df_model.rda"

#if(file.exists(f1))
#  load(f1)
```


# Import data

```{r import}
df_import <- read_xlsx("data_7d.xlsx", range = "C5:LN131")

# list of masses recorded
m <- as.character(
  c(6:7, 9, 22:23, 27, 35, 37, 44:45, 47, 49:56, 58:60, 62:71, 71.5, 72, 72.5, 73, 73.5, 74, 74.5, 75:77, 77.5,
    78, 78.5, 79, 81, 81.5, 82:83, 83.5, 84:92, 94:100, 104:108, 111, 115:116, 118:127, 129, 131, 133:164, 166:172,
    176:177, 179, 187, 189, 203:206, 212:229, 231:233, 238, 248:249)
  )

nm <- paste0(rep(c("m_", "rsd"), times = length(m) * 2), rep(m, each = 2)) 

nm <- c(colnames(df_import)[1:6], nm) 

df_model <- df_import %>%
  magrittr::set_colnames(nm) %>%
  rename(file = "Data File", 
         acq_date = "Acq. Date-Time",
         day = Day,
         type = Type,
         sample = "Sample Name",
         comment = Comment) %>%
  select(file,
         day,
         sample, 
         comment, 
         matches("m_")) %>%
  mutate(sample = replace(sample, sample == "4BW38A", "4BW30A")) %>% # fix typo in original data sheet
  pivot_longer(cols = matches("m_")) %>%
  rename(cps = value,
         mass = name) %>%
  mutate(mass = as.numeric(str_sub(mass, start = 3)))

df_model %>%
  print(10)
```


```{r explore, fig.align = "center", fig.asp= 2, fig.width=8}
df_model %>%
  filter(day == 1) %>%
  ggplot(aes(x = log(cps +.001), y = factor(mass), color = sample)) +
  geom_point() +
  theme_cleveland()
```

























